change spring/damping calculation, added centre of mass option
Dechode/Godot-Advanced-Vehicle pull request #6
Opened 2023-04-18 20:48 UTC by michurebmann

The spring/damper value will now be calculatet based on absolut values, means when you change the spring length, the spring/damp stiffnes will be the same.

when u work with normalized values, the spring/damp stiffness will change when you change the spring length

added a node "CentreOfMass".
it will change the com, based on the nodes position, so you can change the COM without changing the collider size/pos. could manipulate it to represent the fuel consume

2023-04-18 20:49 UTC, michurebmann commented
I hope that's how you do it.

2023-04-19 16:03 UTC, Dechode commented
Hey! Thanks for the pull request. For the most part this seems fine, but ever since Godot 4 it has been possible to set center of gravity of a RigidBody from the inspector, so there is no need for a node to set it. One just needs to set the center_of_mass_mode to custom and you can then specify a Vector3 that will be used as center of mass.  I'll also leave few comments on naming conventions for variables.

2023-04-19 16:11 UTC, michurebmann commented
ok, i did nor know that with the com option... lol.

as far as i know i can change my pull request by change the sugested inputs from you and pull again?

i never done this, where can i see the comments on the naming conventions?

2023-04-19 16:27 UTC, Dechode commented
> as far as i know i can change my pull request by change the sugested inputs from you and pull again?
Yeah thats how i imagine it works, i am actually quite new to collaborating on github myself. I have some experience with gitlab and thats how it was done there. 

The comments should be visible somewhere in this thread and / or in the files changed tab. You were so fast to reply i probably had not written them yet lol

2023-04-20 17:56 UTC, Dechode commented
The dot net property is fine, i can still open the project with non .Net version of Godot. 
Weird that the comments are not showing up. Not even in this thread? I see a section saying "Dechode started a review" and that's where the comments are. I left some comments again in the newest change about typos in comments in code.
Other than that it looks good now, I will try out the changes soon and then merge this after those few typos are corrected.

2023-04-20 18:05 UTC, michurebmann commented on scenes/vehicle/wheel_suspension.gd
> +var spring_speed_mm_per_seconds:float = 0
maybe too long name?

2023-04-20 18:17 UTC, Dechode commented
I can see your comment about variable name maybe being too long. I try to request a review from myself again, maybe that has something to do with my comments not showing up.

2023-04-20 18:24 UTC, michurebmann commented
i see the review request, but thats for you, i cannot open it

2023-04-20 18:26 UTC, Dechode requested changes
Okay maybe you can see all the comments now?

2023-04-20 18:26 UTC, Dechode commented on scenes/vehicle/wheel_suspension.gd
> +var spring_speed_mm_per_seconds:float = 0
Hmm, i think long variable names are fine, if they are descriptive. Which this is IMO. I think it is fine

2023-04-20 18:26 UTC, Dechode commented on scenes/vehicle/base_car.tscn
> -[ext_resource type="AudioStream" path="res://sounds/tres/engine_sample.tres" id="2_om5dm"]
Did the AudioStream get deleted somehow?

2023-04-20 18:26 UTC, Dechode commented on scenes/vehicle/base_car.tscn
> -
Did these get deleted as well? Or just github being weird

2023-04-20 18:26 UTC, Dechode commented on scenes/vehicle/base_car.tscn
> -rear_diff = 2
And did something happen to these as well?

2023-04-20 18:44 UTC, michurebmann commented
now i can see it all!  

well, its weird, my project works just fine,
i think its because i first added a node (com) which mix up all the indexes of the scene.

i will make a complete new pull request, i think it will be better.

can you just reject the pull? i will then re synk the fork and redo the pull, since there are now a lot less changes.
or ho can i undo the pull?

2023-04-20 19:01 UTC, closed without merging